### ISSUE TITLE
Could migration to keyhelp not change database name and db username?

### ISSUE THREAD

**Issue by akong77** [TheCry/i-mscp-keyhelp-migration#5]
Hello,
I found it's migration to keyhelp will auto create database and create db username.But it's will auto change it's name.
origin db name is keo_db.The auto create database is db2_keo_db.
Could use origin database name to create it?

**Comment by TheCry** [comment]
There is a possibility in i-MSCP to put numbers automatically in front of database names and database users. Numbers are not supported as the first digit in KeyHelp. For this reason I need to find a common solution here that does not create problems during migration.

**Comment by akong77** [comment]
Understood.
If I make sure my all database and database username is not in front of have number.Could I set it's no need change it?

**Comment by TheCry** [comment]
You are free to customize the migration script for yourself. As it is, it was written for general use. The risk that there is a number in front is very high and so I will not implement it.
